name: "analyze"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: pubspec.yaml
          architecture: x64
      - run: flutter pub get --enforce-lockfile
      - name: Analyze Dart
        run: flutter analyze --no-pub --no-fatal-infos
